name: Makefile CI

on:
  push:
    tags:
      - "build_*"
      - "r_*"

env:
  CACHE_VERSION: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt install build-essential lv2-dev
    - name: make
      run: make CXXFLAGS='' && tar czf ewisynth-lv2.tar.gz ewisynth.lv2/
    - name: Upload lv2 Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ewisynth-lv2
        path: ./ewisynth.lv2/
        if-no-files-found: warn
    - name: create release
      if: startsWith( ${{ github.ref }}, 'refs/tags/r_')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ewisynth-lv2.tar.gz"
