on:
  push:
    tags:
      - "build_*"
      - "r_*"

jobs:
  linux:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfftw3-dev pkg-config
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: linux-x86_64

  macos:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew update
          brew install fftw pkg-config
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig" >> $GITHUB_ENV
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: macos-universal

  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: choco install fftw
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: win64
