name: Makefile CI

on:
  push:
    tags:
      - "build_*"
      - "r_*"

env:
  CACHE_VERSION: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt install build-essential lv2-dev
    - name: make
      run: make
    - name: Upload lv2 Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ewisynth-lv2
        path: ./ewisynth.lv2/
        if-no-files-found: warn

  modaudio:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up cache
        uses: actions/cache@v3
        id: mpb-cache
        with:
          path: |
            ~/mod-workdir
          key: moddwarf-v${{ env.CACHE_VERSION }}
      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq acl bc curl cvs git mercurial rsync subversion wget bison bzip2 flex gawk gperf gzip help2man nano perl patch tar texinfo unzip automake binutils build-essential cpio libtool libncurses-dev pkg-config python libtool-bin liblo-dev qemu-user-static
          sudo apt-get install -yqq pandoc texlive-latex-recommended texlive-latex-extra
          sudo apt-get clean
      - name: Bootstrap toolchain
        if: steps.mpb-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/moddevices/mod-plugin-builder.git deps/mod-plugin-builder
          sed -i "s/CT_LOG_PROGRESS_BAR=y/CT_LOG_PROGRESS_BAR=n/" deps/mod-plugin-builder/toolchain/*.config
          $(pwd)/deps/mod-plugin-builder/bootstrap.sh moddwarf minimal && $(pwd)/deps/mod-plugin-builder/.clean-install.sh moddwarf
      - name: Build for modaudio
        if: steps.mpb-cache.outputs.cache-hit == 'true'
        run: |
          make
      - name: Pack binaries
        if: steps.mpb-cache.outputs.cache-hit == 'true'
        run: |
          tar -c -h --hard-dereference -z -f ${{ github.event.repository.name }}-moddwarf-${{ github.event.pull_request.number }}.tar.gz -C bin $(ls bin | grep lv2)
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-moddwarf-${{ github.event.pull_request.number }}
          path: |
            *.tar.gz
